name: mais_saude_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  flutter_bloc: ^2.1.1
  bloc: ^2.0.0
  equatable: ^1.0.1
  get: ^1.6.2

  # UI
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true